script: "./script/cibuild"
language: ruby
rvm:
- 2.4.0
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
notifications:
  email: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GIT_AUTHOR_NAME="Brandon Keepers"
  - GIT_AUTHOR_EMAIL="bkeepers@github.com"
sudo: false
cache: bundler
